spring.application.name=backend

# Server Settings
server.port=3848

# File Upload Settings (for ISO files)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10GB
spring.servlet.multipart.max-request-size=10GB
